PREFERENCES:
    SCORE_GOAL: 6500        # The amount of points you want to get
    DO_TASKS: True          # Activate the tasks
    DO_SEARCHES: True       # Activate the searches
    AUTO_UPDATE : False     # (Needed Git and have done 'git clone') Automatically update the program from Github
    ALLOW_VPN : False       # Duplicate the points using VPN - (manual mode)
    IPVANISH : False        # (Not yet) Only if you have IpVanish opened - (automatic mode)
    MULTIACCOUNT : False    # (Not yet) Execute the script for all the accounts in 'accounts.json'